service: apiDbMagic
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1
  stage: ${opt:stage, 'dev'}    
  # iam:
  #   role:
  #     statements:
  #       - Effect: Allow
  #         Action:
  #           - dynamodb:*
  #         Resource: 'arn:aws:dynamodb:eu-west-1:*:*'
  environment:
    USERS_TABLE: ${self:custom.tableName}
    STAGE: ${self:provider.stage}    
    TABLE_CARDS: ${self:custom.tableName}
    SET_INDEX: set-card-index
    NAME_INDEX: name-card-index

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: 'arn:aws:dynamodb:eu-west-1:*:*'

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /{proxy+}
          method: 'any'
          cors: false
    #environment:
      #TABLE_CARDS: ${self:custom.tableName}
  task:
    handler: task.main
    events:
      - schedule: cron(18 2 * * ? *)
      #1h menos en pre

    environment:
      MGC_COLLECTIONS: 'IKO;GRN;ISD'
      URL_API: https://api.scryfall.com/cards/search
      #TABLE_CARDS: ${self:custom.tableName}

resources:
  Resources:
    cardTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: name
            AttributeType: S
          - AttributeName: set
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          # - AttributeName: set
          #   KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: name-card-index
            KeySchema:
              - AttributeName: name
                KeyType: HASH
            Projection:
              ProjectionType: 'ALL'
          - IndexName: set-card-index
            KeySchema:
              - AttributeName: set
                KeyType: HASH
            Projection:
              ProjectionType: 'ALL'
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
        
custom:
  dynamodb:
    stages:
      - ${self:provider.stage}
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
  tableName: 'cards-${sls:stage}'

plugins:
  - serverless-dynamodb-local
  - serverless-offline